apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rdicidr
  namespace: production
  labels:
    app:  my_app
spec:
  selector:
    matchLabels:
      app: my_app
  replicas: 2
  template:
    metadata:
      labels:
        app:  my_app
    spec:
      containers:
      - name:  rdicidr
        image:  yohanan91/devops-ci:latest
        envFrom:
        - secretRef:
            name: mysecret
        ports:
        - containerPort:  3000
          name:  rdicidr
        
--- 
apiVersion: v1
kind: Service
metadata:
  name: rdicidr
  namespace: production
spec:
  selector:
    app: my_app
  type: ClusterIP
  ports:
  - name: my_app
    protocol: TCP
    port: 3000
    targetPort: 8080
